name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Autotools environment
        run: |
          apt-get update
          apt-get install -y automake
          apt-get install -y autoconf
      - name: configure
        run: |
          aclocal
          autoconf
          automake -c -a
      - name: zip
        run: |
          zip ../dotfiles.zip *
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ../dotfiles.zip
          asset_name: dotfiles.zip
          asset_content_type: application/zip
